version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      APP_SECRET: changeme
      DATABASE_URL: mysql://root:root@db:3306/vite_et_gourmand
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: vite_et_gourmand
      MAILER_DSN: null://null
    depends_on:
      - db
      - mongo

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vite_et_gourmand
    ports:
      - "3306:3306"
    volumes:
      - ./database/vite_et_gourmand.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"